### ISSUE TITLE
Any examples? Looking to use this to control 2 video players, and keep the same actions / reducers for both?

### ISSUE THREAD

**Issue by joshuairl** [9technology/redux-namespaces#1]

**Comment by billypownall** [comment]
Hi @joshuairl,

There is a very basic example in the readme, (here's)[https://gist.github.com/billypownall/ac4f9f184a25ab562b2689ad379abb89] a more thorough one I threw together though.

We call createActions inside the container to namespace it based off a prop (the storeKey in this case) so that they'll each have their own state in the store but share the same actions/reducer.

**Comment by tur-nr** [comment]
See #4
